#!/bin/sh

regex='@neoxam\.com$'
email=$GIT_AUTHOR_EMAIL

if [[ $email =~ $regex ]];
then
  echo "Your email $email satisfay GIT Policy"
  exit 0
else
  echo "Your email $email doesn't satisfay GIT Policy"
  exit 1
fi
